on:
  push:

jobs:
  fifo-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Fifo on AUR repo
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: fifo-bin
          pkgbuild: ./PKGBUILD
          commit_username: snaildos
          commit_email: snaildos@snaildos.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

# v3